"""Executable metric formulas generated from line_item_metric_registry.json.

The registry controls public line item and metric IDs. The formulas are
ported from the legacy executable formula set with registry rename_map
applied mechanically.
"""
from __future__ import annotations

_LINE_ITEM_RENAMES = {'accounts_receivable': 'accounts_receivable_net',
 'allowance_doubtful': 'allowance_for_doubtful_accounts',
 'amortization_goodwill': 'amortization_of_goodwill',
 'amortization_intangibles': 'amortization_of_intangibles',
 'analyst_revisions_90d': 'analyst_estimate_revisions_90_day',
 'aoci': 'accumulated_other_comprehensive_income',
 'apic': 'additional_paid_in_capital',
 'asset_impairment_cf': 'asset_impairment_addback_cashflow',
 'basic_eps': 'earnings_per_share_basic',
 'basic_shares': 'shares_outstanding_basic',
 'beta_5y': 'market_beta_5_year',
 'capex': 'capital_expenditures',
 'capital_lease_liab': 'finance_lease_liability',
 'cash': 'cash_and_cash_equivalents',
 'cet1_ratio': 'common_equity_tier1_ratio',
 'cff': 'cash_flow_from_financing',
 'cfi': 'cash_flow_from_investing',
 'cfo': 'cash_flow_from_operations',
 'change_ap': 'change_in_accounts_payable',
 'change_ar': 'change_in_accounts_receivable',
 'change_inventory': 'change_in_inventory',
 'change_other_wc': 'change_in_other_working_capital',
 'cogs': 'cost_of_goods_sold',
 'current_ltd': 'long_term_debt_current_portion',
 'da_addback': 'depreciation_and_amortization_addback_cashflow',
 'debt_issuance': 'debt_issuance_proceeds',
 'deferred_revenue_cur': 'deferred_revenue_current',
 'deferred_tax_cf': 'deferred_tax_cashflow_impact',
 'deferred_tax_liab': 'deferred_tax_liability',
 'deposits_total': 'total_deposits',
 'diluted_eps': 'earnings_per_share_diluted',
 'diluted_shares': 'shares_outstanding_diluted',
 'directors_bonus_jp': 'directors_bonus_japan_gaap',
 'dps': 'dividends_per_share',
 'ebit': 'earnings_before_interest_taxes',
 'ebitda': 'earnings_before_interest_taxes_depreciation_amortization',
 'ebitdar': 'earnings_before_interest_taxes_depreciation_amortization_rent',
 'ebt': 'earnings_before_taxes',
 'employees': 'employee_count',
 'eps_consensus_fwd1y': 'earnings_per_share_consensus_forward_1_year',
 'eps_consensus_fwd2y': 'earnings_per_share_consensus_forward_2_year',
 'equity_in_earnings': 'equity_in_earnings_of_affiliates',
 'equity_investments': 'equity_method_investments',
 'equity_issuance': 'equity_issuance_proceeds',
 'excess_cash': 'excess_cash_above_operating_needs',
 'fcf': 'free_cash_flow',
 'fcfe': 'free_cash_flow_to_equity',
 'fx_gain_loss': 'foreign_exchange_gain_loss',
 'ga_expense': 'general_and_administrative_expense',
 'gain_loss_asset_sale': 'gain_loss_on_asset_sale_cashflow',
 'institutional_own_pct': 'institutional_ownership_percent',
 'intangible_assets': 'intangible_assets_net',
 'interest_paid_cf': 'interest_paid_cashflow',
 'inventory': 'inventory_total',
 'inventory_finished': 'inventory_finished_goods',
 'inventory_wip': 'inventory_work_in_progress',
 'knowledge_capital': 'knowledge_capital_intangible',
 'labor_expense': 'labor_and_employee_costs',
 'lease_adjusted_debt': 'total_debt_lease_adjusted',
 'loans_total': 'total_loans_net',
 'market_cap': 'market_capitalization',
 'minority_interest_exp': 'minority_interest_expense',
 'nci_equity': 'noncontrolling_interest_equity',
 'net_change_cash': 'net_change_in_cash',
 'net_income_common': 'net_income_attributable_to_common',
 'noa': 'net_operating_assets',
 'nopat': 'net_operating_profit_after_tax',
 'npl_ratio': 'nonperforming_loan_ratio_filed',
 'operating_lease_liab': 'operating_lease_liability',
 'ordinary_income_jp': 'ordinary_income_japan_gaap',
 'org_capital': 'organizational_capital_intangible',
 'ppe_gross': 'property_plant_equipment_gross',
 'ppe_net': 'property_plant_equipment_net',
 'price': 'stock_price',
 'provision_loan_losses': 'provision_for_loan_losses',
 'purchase_investments': 'purchase_of_investments',
 'rd_expense': 'research_and_development_expense',
 'rent_expense': 'rent_and_lease_expense',
 'rou_assets': 'right_of_use_assets',
 'rwa': 'risk_weighted_assets',
 'sale_investments': 'sale_of_investments',
 'sbc': 'stock_based_compensation',
 'sbc_addback': 'stock_based_compensation_addback_cashflow',
 'sga': 'selling_general_and_administrative_expense',
 'short_interest_pct': 'short_interest_percent_of_float',
 'sm_expense': 'sales_and_marketing_expense',
 'special_items_jp': 'special_gains_losses_japan_gaap',
 'tangible_equity': 'tangible_book_equity',
 'tax_provision': 'income_tax_provision',
 'taxes_paid_cf': 'taxes_paid_cashflow',
 'tier1_leverage': 'tier1_leverage_ratio',
 'total_current_liab': 'total_current_liabilities',
 'total_debt': 'total_financial_debt',
 'unlevered_fcf': 'free_cash_flow_unlevered',
 'working_capital': 'working_capital_gross'}

_METRIC_RENAMES = {'accrual_volatility': 'accrual_volatility_5_year',
 'adj_ebitda': 'adjusted_earnings_before_interest_taxes_depreciation_amortization',
 'altman_z': 'altman_z_score',
 'analyst_rev': 'analyst_estimate_revisions_90_day_metric',
 'beneish_m': 'beneish_m_score',
 'beta_metric': 'market_beta',
 'book_to_market': 'book_to_market',
 'bvps_growth_yoy': 'book_value_per_share_growth_year_over_year',
 'cash_flow_yield': 'cash_flow_from_operations_yield',
 'cash_tax_rate_metric': 'cash_tax_rate',
 'ccc': 'cash_conversion_cycle',
 'cet1_metric': 'common_equity_tier1_ratio_metric',
 'change_noa': 'change_in_net_operating_assets',
 'cma_factor': 'conservative_investment_cma_fama_french',
 'croic': 'cash_return_on_invested_capital',
 'debt_to_equity': 'total_financial_debt_to_equity',
 'deferred_rev_growth': 'deferred_revenue_growth_vs_revenue_growth',
 'dio': 'days_inventory_outstanding',
 'div_growth_1y': 'dividend_growth_1_year',
 'dividend_payout': 'dividend_payout_ratio',
 'dpo': 'days_payable_outstanding',
 'dso': 'days_sales_outstanding',
 'dso_trend': 'days_sales_outstanding_trend',
 'earnings_surprise_m': 'earnings_surprise_metric',
 'ebit_growth_yoy': 'operating_income_growth_year_over_year',
 'ebit_margin': 'operating_margin',
 'ebitda_growth_yoy': 'earnings_before_interest_taxes_depreciation_amortization_growth_year_over_year',
 'ebitda_margin': 'earnings_before_interest_taxes_depreciation_amortization_margin',
 'efficiency_ratio': 'efficiency_ratio_bank',
 'eps_cagr_3y': 'earnings_per_share_diluted_compound_annual_growth_rate_3_year',
 'eps_growth_yoy': 'earnings_per_share_diluted_growth_year_over_year',
 'ev_ebit': 'enterprise_value_to_earnings_before_interest_taxes',
 'ev_ebitda': 'enterprise_value_to_earnings_before_interest_taxes_depreciation_amortization',
 'ev_gross_profit': 'enterprise_value_to_gross_profit',
 'ev_ic': 'enterprise_value_to_invested_capital',
 'ev_invested_capital': 'enterprise_value_to_invested_capital',
 'ev_nopat': 'enterprise_value_to_net_operating_profit_after_tax',
 'ev_sales': 'enterprise_value_to_revenue',
 'ext_fin_to_assets': 'external_financing_to_assets',
 'external_financing': 'external_financing_signal',
 'fcf_growth_yoy': 'free_cash_flow_growth_year_over_year',
 'fcf_payout': 'free_cash_flow_payout_ratio',
 'fcf_yield': 'free_cash_flow_yield',
 'fixed_charge_cov': 'fixed_charge_coverage',
 'gp_over_assets': 'gross_profitability_novy_marx',
 'gw_amort_addback': 'goodwill_amortisation_addback',
 'ifrs16_interest': 'ifrs16_lease_interest_split',
 'incremental_roic': 'incremental_return_on_invested_capital',
 'inv_sales_trend': 'inventory_to_revenue_trend',
 'inv_to_assets': 'investment_to_assets',
 'ivol': 'idiosyncratic_volatility',
 'keijo_rieki': 'ordinary_income_japan_gaap_metric',
 'knowledge_cap_metric': 'knowledge_capital_metric_perpetual_inventory',
 'lease_adj_debt': 'lease_adjusted_total_debt',
 'loan_deposit_ratio': 'loan_to_deposit_ratio',
 'mktcap_tangible_assets': 'market_capitalization_to_tangible_assets',
 'net_debt_ebitda': 'net_debt_to_earnings_before_interest_taxes_depreciation_amortization',
 'net_margin': 'net_profit_margin',
 'net_stock_issues': 'net_stock_issues_signal',
 'ni_growth_yoy': 'net_income_growth_year_over_year',
 'nim': 'net_interest_margin',
 'noa_ratio': 'net_operating_assets_ratio',
 'nopat_metric': 'net_operating_profit_after_tax',
 'normalized_ebit': 'normalized_earnings_before_interest_taxes',
 'operating_accruals': 'operating_accruals',
 'operating_profitability': 'operating_profitability_rmw_fama_french',
 'org_cap_metric': 'organizational_capital_metric_perpetual_inventory',
 'pb_ratio': 'price_to_book',
 'pcf_ratio': 'price_to_cash_flow_from_operations',
 'pe_forward_1y': 'price_to_earnings_forward_1_year',
 'pe_forward_2y': 'price_to_earnings_forward_2_year',
 'pe_trailing': 'price_to_earnings_trailing',
 'pead': 'post_earnings_announcement_drift',
 'peg_ratio': 'price_to_earnings_growth',
 'piotroski_f': 'piotroski_f_score',
 'price_fcf': 'price_to_free_cash_flow',
 'price_mom_12m_1m': 'price_momentum_12_month_minus_1_month',
 'price_mom_6m': 'price_momentum_6_month',
 'price_nwc': 'price_to_net_working_capital',
 'price_rd': 'price_to_research_and_development',
 'provision_coverage': 'provision_coverage_ratio',
 'ps_ratio': 'price_to_sales',
 'q_ia_factor': 'investment_factor_ia_hxz',
 'q_roe_factor': 'quality_roe_factor_hxz',
 'rd_capitalization': 'research_and_development_capitalization',
 'revenue_cagr_3y': 'revenue_compound_annual_growth_rate_3_year',
 'revenue_cagr_5y': 'revenue_compound_annual_growth_rate_5_year',
 'revenue_growth_yoy': 'revenue_growth_year_over_year',
 'rmw_factor': 'operating_profitability_rmw_fama_french',
 'roa': 'return_on_assets',
 'roce': 'return_on_capital_employed',
 'roe': 'return_on_equity',
 'roic': 'return_on_invested_capital',
 'rona': 'return_on_net_operating_assets',
 'sales_to_price': 'revenue_to_market_capitalization',
 'sloan_ratio': 'sloan_accruals_ratio',
 'sustainable_growth': 'sustainable_growth_rate',
 'tangible_pb': 'tangible_price_to_book',
 'tax_avoidance': 'cash_tax_avoidance_long_window',
 'tokubetsu': 'special_gains_losses_japan_gaap_metric',
 'total_shareholder_yield': 'total_shareholder_yield',
 'total_vol': 'total_volatility_252_day'}

_L1_FORMULAS = {'cash_tax_rate': '_div(taxes_paid_cashflow, earnings_before_taxes)',
 'earnings_before_interest_taxes_depreciation_amortization': 'earnings_before_interest_taxes + '
                                                             'depreciation_and_amortization_addback_cashflow',
 'earnings_before_interest_taxes_depreciation_amortization_rent': 'earnings_before_interest_taxes_depreciation_amortization '
                                                                  '+ rent_and_lease_expense',
 'enterprise_value': 'market_capitalization + net_debt + (noncontrolling_interest_equity or 0) - '
                     '(equity_method_investments or 0)',
 'excess_cash_above_operating_needs': 'max(0.0, (cash_and_cash_equivalents or 0) - 0.02 * (revenue or 0)) if revenue '
                                      'else None',
 'free_cash_flow': 'cash_flow_from_operations - _abs_capex(capital_expenditures)',
 'free_cash_flow_unlevered': 'net_operating_profit_after_tax + (depreciation_and_amortization_addback_cashflow or 0) - '
                             '_abs_capex(capital_expenditures or 0)',
 'gross_profit': 'revenue - abs(cost_of_goods_sold or 0)',
 'invested_capital': 'total_equity + net_debt',
 'net_debt': 'total_financial_debt - (cash_and_cash_equivalents or 0) - (short_term_investments or 0)',
 'net_operating_assets': '(total_assets - (cash_and_cash_equivalents or 0) - (short_term_investments or 0)) - '
                         '(total_liabilities - ((short_term_debt or 0) + (long_term_debt_current_portion or 0) + '
                         '(long_term_debt or 0) + (operating_lease_liability or 0)))',
 'net_operating_profit_after_tax': 'earnings_before_interest_taxes * (1 - _tax_rate(cash_tax_rate))',
 'net_working_capital': '(total_current_assets - (cash_and_cash_equivalents or 0) - (short_term_investments or 0)) - '
                        '(total_current_liabilities - (short_term_debt or 0) - (long_term_debt_current_portion or 0))',
 'tangible_book_equity': 'total_equity - (goodwill or 0) - (intangible_assets_net or 0)',
 'total_debt_lease_adjusted': 'total_financial_debt + (operating_lease_liability or 0)',
 'total_financial_debt': '(short_term_debt or 0) + (long_term_debt_current_portion or 0) + (long_term_debt or 0)',
 'working_capital_gross': 'total_current_assets - total_current_liabilities'}

_METRIC_FORMULAS = {'adjusted_earnings_before_interest_taxes_depreciation_amortization': 'earnings_before_interest_taxes_depreciation_amortization '
                                                                      '+ (stock_based_compensation or 0) + '
                                                                      '(restructuring_charges or 0) + '
                                                                      '(asset_impairment or 0)',
 'asset_growth': 'pct_change(total_assets, total_assets_prev)',
 'asset_turnover': '_div(revenue, total_assets)',
 'book_to_market': '_div(total_equity, market_capitalization)',
 'book_value_per_share_growth_year_over_year': 'pct_change(total_equity, total_equity_prev)',
 'buyback_yield': '_div(abs(share_repurchases or 0), market_capitalization)',
 'cash_conversion_cycle': 'days_sales_outstanding + days_inventory_outstanding - days_payable_outstanding if '
                          'days_sales_outstanding is not None and days_inventory_outstanding is not None and '
                          'days_payable_outstanding is not None else None',
 'cash_flow_from_operations_yield': '_div(cash_flow_from_operations, market_capitalization)',
 'cash_ratio': '_div((cash_and_cash_equivalents or 0) + (short_term_investments or 0), total_current_liabilities)',
 'cash_return_on_invested_capital': '_div(free_cash_flow, invested_capital)',
 'cash_tax_avoidance_long_window': '_div(taxes_paid_cashflow, earnings_before_taxes)',
 'cash_tax_rate': 'cash_tax_rate',
 'change_in_net_operating_assets': '_div((net_operating_assets or 0) - (noa_prev or 0), ((total_assets or 0) + '
                                   '(total_assets_prev or 0)) / 2) if total_assets_prev else None',
 'common_equity_tier1_ratio_metric': 'common_equity_tier1_ratio',
 'conservative_investment_cma_fama_french': '_div(total_assets_prev - total_assets, abs(total_assets_prev)) if '
                                            'total_assets_prev else None',
 'current_ratio': '_div(total_current_assets, total_current_liabilities)',
 'days_inventory_outstanding': '_div((inventory_total or 0) * 365, abs(cost_of_goods_sold) if cost_of_goods_sold is '
                               'not None else None)',
 'days_payable_outstanding': '_div((accounts_payable or 0) * 365, abs(cost_of_goods_sold) if cost_of_goods_sold is not '
                             'None else None)',
 'days_sales_outstanding': '_div((accounts_receivable_net or 0) * 365, revenue)',
 'days_sales_outstanding_trend': '_div(accounts_receivable_net * 365, revenue) - _div(accounts_receivable_prev * 365, '
                                 'revenue_prev) if accounts_receivable_prev and revenue_prev else None',
 'deferred_revenue_growth_vs_revenue_growth': '_div(deferred_revenue_current, revenue) - '
                                              '_div(deferred_revenue_cur_prev, revenue_prev) if '
                                              'deferred_revenue_cur_prev and revenue_prev else None',
 'dividend_growth_1_year': 'pct_change(dividends_per_share, dps_prev)',
 'dividend_payout_ratio': '_div(abs(dividends_paid or 0), net_income_attributable_to_common) if '
                          'net_income_attributable_to_common else _div(abs(dividends_per_share or 0), '
                          'earnings_per_share_diluted)',
 'dividend_yield': '_div(abs(dividends_per_share), stock_price) if dividends_per_share else _div(abs(dividends_paid or '
                   '0), market_capitalization)',
 'earnings_before_interest_taxes_depreciation_amortization_growth_year_over_year': 'pct_change(earnings_before_interest_taxes_depreciation_amortization, '
                                                                                   'ebitda_prev)',
 'earnings_before_interest_taxes_depreciation_amortization_margin': '_div(earnings_before_interest_taxes_depreciation_amortization, '
                                                                    'revenue)',
 'earnings_per_share_diluted_compound_annual_growth_rate_3_year': 'cagr(earnings_per_share_diluted, diluted_eps_3y, 3)',
 'earnings_per_share_diluted_growth_year_over_year': 'pct_change(earnings_per_share_diluted, diluted_eps_prev)',
 'earnings_yield': '_div(earnings_before_interest_taxes, enterprise_value)',
 'enterprise_value_to_earnings_before_interest_taxes': '_div(enterprise_value, earnings_before_interest_taxes)',
 'enterprise_value_to_earnings_before_interest_taxes_depreciation_amortization': '_div(enterprise_value, '
                                                                                 'earnings_before_interest_taxes_depreciation_amortization)',
 'enterprise_value_to_gross_profit': '_div(enterprise_value, gross_profit)',
 'enterprise_value_to_invested_capital': '_div(enterprise_value, invested_capital)',
 'enterprise_value_to_net_operating_profit_after_tax': '_div(enterprise_value, net_operating_profit_after_tax)',
 'enterprise_value_to_revenue': '_div(enterprise_value, revenue)',
 'external_financing_signal': '_div(((total_equity or 0) - (total_equity_prev or 0)) + ((total_financial_debt or 0) - '
                              '(total_debt_prev or 0)), total_assets)',
 'external_financing_to_assets': '_div(((debt_issuance_proceeds or 0) - abs(debt_repayment or 0)) + '
                                 '((equity_issuance_proceeds or 0) - abs(share_repurchases or 0)), total_assets)',
 'fixed_asset_turnover': '_div(revenue, property_plant_equipment_net)',
 'fixed_charge_coverage': '_div((earnings_before_interest_taxes or 0) + abs(rent_and_lease_expense or 0), '
                          'abs(interest_expense or 0) + abs(rent_and_lease_expense or 0))',
 'free_cash_flow_growth_year_over_year': 'pct_change(free_cash_flow, fcf_prev)',
 'free_cash_flow_payout_ratio': '_div(abs(dividends_paid or 0), free_cash_flow)',
 'free_cash_flow_yield': '_div(free_cash_flow, market_capitalization)',
 'goodwill_amortisation_addback': 'amortization_of_goodwill',
 'gross_margin': '_div(gross_profit, revenue)',
 'gross_profitability_novy_marx': '_div(gross_profit, total_assets)',
 'ifrs16_lease_interest_split': '_div(interest_expense * (operating_lease_liability or 0), (total_financial_debt or 0) '
                                '+ (operating_lease_liability or 0)) if interest_expense and operating_lease_liability '
                                'else None',
 'incremental_return_on_invested_capital': '_div((net_operating_profit_after_tax or 0) - (nopat_prev or 0), '
                                           'abs((invested_capital or 0) - (invested_capital_prev or 0))) if '
                                           'invested_capital_prev is not None and invested_capital is not None and '
                                           'abs((invested_capital or 0) - (invested_capital_prev or 0)) > 0 else None',
 'interest_coverage': '_div(earnings_before_interest_taxes, abs(interest_expense) if interest_expense is not None else '
                      'None)',
 'inventory_to_revenue_trend': '_div(inventory_total, revenue) - _div(inventory_prev, revenue_prev) if inventory_prev '
                               'and revenue_prev else None',
 'inventory_turnover': '_div(abs(cost_of_goods_sold) if cost_of_goods_sold is not None else None, inventory_total)',
 'investment_factor_ia_hxz': 'pct_change(total_assets, total_assets_prev)',
 'investment_to_assets': '_div(((property_plant_equipment_net or 0) - (ppe_net_prev or 0)) + ((inventory_total or 0) - '
                         '(inventory_prev or 0)), total_assets)',
 'knowledge_capital_metric_perpetual_inventory': 'research_and_development_expense',
 'lease_adjusted_total_debt': 'total_debt_lease_adjusted',
 'loan_to_deposit_ratio': '_div(total_loans_net, total_deposits)',
 'market_capitalization_to_tangible_assets': '_div(market_capitalization, total_assets - (goodwill or 0) - '
                                             '(intangible_assets_net or 0))',
 'net_debt_to_earnings_before_interest_taxes_depreciation_amortization': '_div(net_debt, '
                                                                         'earnings_before_interest_taxes_depreciation_amortization)',
 'net_income_growth_year_over_year': 'pct_change(net_income_attributable_to_common, net_income_common_prev)',
 'net_interest_margin': '_div(net_interest_income, total_assets)',
 'net_operating_assets_ratio': '_div(net_operating_assets, total_assets)',
 'net_profit_margin': '_div(net_income_attributable_to_common, revenue)',
 'net_stock_issues_signal': 'pct_change(shares_outstanding_diluted, diluted_shares_prev)',
 'normalized_earnings_before_interest_taxes': 'earnings_before_interest_taxes + (restructuring_charges or 0) + '
                                              '(asset_impairment or 0)',
 'operating_accruals': '_div(((total_current_assets or 0) - (total_current_assets_prev or 0)) - '
                       '((cash_and_cash_equivalents or 0) - (cash_prev or 0)) - (((total_current_liabilities or 0) - '
                       '(total_current_liab_prev or 0))    - ((short_term_debt or 0) - (short_term_debt_prev or 0))    '
                       '- ((long_term_debt_current_portion or 0) - (current_ltd_prev or 0))) - '
                       '(depreciation_and_amortization_addback_cashflow or 0), total_assets)',
 'operating_income_growth_year_over_year': 'pct_change(earnings_before_interest_taxes, ebit_prev)',
 'operating_margin': '_div(earnings_before_interest_taxes, revenue)',
 'operating_profitability_rmw_fama_french': '_div((revenue or 0) - abs(cost_of_goods_sold or 0) - '
                                            'abs(selling_general_and_administrative_expense or 0) - '
                                            'abs(interest_expense or 0), total_equity)',
 'ordinary_income_japan_gaap_metric': 'ordinary_income_japan_gaap',
 'organizational_capital_metric_perpetual_inventory': 'selling_general_and_administrative_expense',
 'payables_turnover': '_div(abs(cost_of_goods_sold) if cost_of_goods_sold is not None else None, accounts_payable)',
 'pretax_margin': '_div(earnings_before_taxes, revenue)',
 'price_momentum_12_month_minus_1_month': 'price_momentum_12_month_minus_1_month',
 'price_momentum_6_month': 'price_momentum_6_month',
 'price_to_book': '_div(market_capitalization, total_equity)',
 'price_to_cash_flow_from_operations': '_div(market_capitalization, cash_flow_from_operations)',
 'price_to_earnings_growth': '_div(price_to_earnings_trailing, revenue_compound_annual_growth_rate_3_year * 100) if '
                             'revenue_compound_annual_growth_rate_3_year and '
                             'revenue_compound_annual_growth_rate_3_year > 0 else None',
 'price_to_earnings_trailing': '_div(market_capitalization, net_income_attributable_to_common) if '
                               'net_income_attributable_to_common else _div(stock_price, earnings_per_share_diluted)',
 'price_to_free_cash_flow': '_div(market_capitalization, free_cash_flow)',
 'price_to_net_working_capital': '_div(market_capitalization, working_capital_gross)',
 'price_to_research_and_development': '_div(market_capitalization, research_and_development_expense)',
 'price_to_sales': '_div(market_capitalization, revenue)',
 'quality_roe_factor_hxz': '_div(net_income_attributable_to_common, total_equity)',
 'quick_ratio': '_div(total_current_assets - (inventory_total or 0), total_current_liabilities)',
 'receivables_turnover': '_div(revenue, accounts_receivable_net)',
 'research_and_development_capitalization': 'research_and_development_expense',
 'return_on_assets': '_div(net_income, total_assets)',
 'return_on_capital_employed': '_div(earnings_before_interest_taxes, (total_assets or 0) - (total_current_liabilities '
                               'or 0))',
 'return_on_equity': '_div(net_income_attributable_to_common, total_equity)',
 'return_on_invested_capital': '_div(net_operating_profit_after_tax, invested_capital)',
 'return_on_net_operating_assets': '_div(net_operating_profit_after_tax, net_operating_assets)',
 'revenue_compound_annual_growth_rate_3_year': 'cagr(revenue, revenue_3y, 3)',
 'revenue_compound_annual_growth_rate_5_year': 'cagr(revenue, revenue_5y, 5)',
 'revenue_growth_year_over_year': 'pct_change(revenue, revenue_prev)',
 'sloan_accruals_ratio': '_div((net_income or 0) - (cash_flow_from_operations or 0), total_assets)',
 'special_gains_losses_japan_gaap_metric': 'special_gains_losses_japan_gaap',
 'sustainable_growth_rate': '_div(net_income_attributable_to_common, total_equity) * (1 - min(abs(_div(dividends_paid '
                            'or 0, net_income_attributable_to_common) or 0), 1.0)) if '
                            'net_income_attributable_to_common and total_equity else None',
 'tangible_price_to_book': '_div(market_capitalization, tangible_book_equity)',
 'total_financial_debt_to_equity': '_div(total_financial_debt, total_equity)',
 'total_shareholder_yield': '(dividend_yield or 0) + (buyback_yield or 0) if (dividend_yield is not None or '
                            'buyback_yield is not None) else None'}

_METRIC_FORMULAS.update({
 'capital_expenditure_intensity': '_div(abs(capital_expenditures), revenue) if capital_expenditures is not None else None',
 'capital_expenditure_to_depreciation': '_div(abs(capital_expenditures), depreciation_and_amortization_addback_cashflow) if capital_expenditures is not None else None',
 'capital_expenditure_to_depreciation_utilities': '_div(abs(capital_expenditures), depreciation_and_amortization_addback_cashflow) if capital_expenditures is not None else None',
 'earnings_before_interest_taxes_depreciation_amortization_minus_capital_expenditures': 'earnings_before_interest_taxes_depreciation_amortization - abs(capital_expenditures) if earnings_before_interest_taxes_depreciation_amortization is not None and capital_expenditures is not None else None',
 'effective_tax_rate': '_div(abs(income_tax_provision), earnings_before_taxes) if income_tax_provision is not None else None',
 'gross_profit_growth_year_over_year': 'pct_change(gross_profit, gross_profit_prev)',
 'net_income_growth_year_over_year': 'pct_change(net_income_attributable_to_common if net_income_attributable_to_common is not None else net_income, net_income_common_prev if net_income_common_prev is not None else net_income_prev)',
 'net_income_per_employee': '_div(net_income_attributable_to_common if net_income_attributable_to_common is not None else net_income, employee_count)',
 'net_profit_margin': '_div(net_income_attributable_to_common if net_income_attributable_to_common is not None else net_income, revenue)',
 'research_and_development_intensity': '_div(abs(research_and_development_expense), revenue) if research_and_development_expense is not None else None',
 'research_and_development_intensity_technology': '_div(abs(research_and_development_expense), revenue) if research_and_development_expense is not None else None',
 'revenue_per_employee': '_div(revenue, employee_count)',
 'return_on_equity': '_div(net_income_attributable_to_common if net_income_attributable_to_common is not None else net_income, total_equity)',
 'rule_of_40_score': '(revenue_growth_year_over_year or 0) + (earnings_before_interest_taxes_depreciation_amortization_margin or 0) if revenue_growth_year_over_year is not None or earnings_before_interest_taxes_depreciation_amortization_margin is not None else None',
 'stock_based_compensation_as_percent_of_revenue': '_div(stock_based_compensation, revenue)',
 'sustainable_growth_rate': '_div(net_income_attributable_to_common if net_income_attributable_to_common is not None else net_income, total_equity) * (1 - min(abs(_div(dividends_paid or 0, net_income_attributable_to_common if net_income_attributable_to_common is not None else net_income) or 0), 1.0)) if (net_income_attributable_to_common is not None or net_income is not None) and total_equity else None',
})

_METRIC_PRIMARY_REQUIRED = {'dividend_payout_ratio': ['net_income_attributable_to_common'],
 'dividend_yield': ['dividends_per_share'],
 'price_to_earnings_trailing': ['net_income_attributable_to_common']}
